#!/usr/bin/env bash

set -euo pipefail

export location="$(pwd)"

git submodule update --init --recursive .

# Run dotbot
SHELL=sh ./submodules/dotbot/bin/dotbot -c default.yaml

# Setup vim
vim +PlugInstall +qall now

# Install rust so we can get just
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
