#!/usr/bin/env bash

set -euo pipefail

export location="$(pwd)"

git submodule init
git submodule update --init --recursive .

# Run dotbot
SHELL=sh ./submodules/dotbot/bin/dotbot -c default.yaml

# Setup vim
vim +PlugInstall +qall now

# Install just
curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to $location/bin
