- clean:
    - '~'
    - ~/.cargo
    - ~/.ssh
    - ~/bin


- link:
  # ~/.bashrc: etc/bashrc
    ~/.bash_logout:
        path: etc/bash_logout
        force: true
    ~/.gitconfig: etc/gitconfig
      # ~/.profile: etc/profile
    ~/.ssh/config:
        path: etc/ssh/config
        create: true
    ~/.tmux.conf: submodules/tmux/.tmux.conf
    ~/.tmux.conf.local: etc/tmux/tmux.conf.local
    ~/.vim: etc/vim
    ~/.vimrc:
        path: etc/vimrc
        create: true
    ~/.zsh: etc/zsh
    ~/.zshrc:
        path: etc/zsh/zshrc
        force: true
    ~/bin:
        path: bin/
    ~/.config/starship.toml:
        path: etc/starship.toml
        create: true
    ~/.config/nvim: config/nvim

- shell:
  - |
    OS_CONFIG=os/`uname | tr '[:upper:]' '[:lower:]'`/default.yaml
    if [[ -f $OS_CONFIG ]]; then
      ./submodules/dotbot/bin/dotbot -c $OS_CONFIG
    fi
  - |
    HOST_CONFIG=box/$HOST/default.yaml
    if [[ -f $HOST_CONFIG ]]; then
      ./submodules/dotbot/bin/dotbot -c $HOST_CONFIG
    fi
  - chmod 700 ~/.vim
  - chmod 700 ~/.ssh
  - chmod 600 ~/.ssh/config
