# --------------------------------
#
# DO NOT EDIT THIS FILE.
# If you want to make changes, do so in the custom/zsh directory.
# Fork and send pull requests to add features and fix bugs. Thanks!
#
# ================================

# Don't change. The following determines where YADR is installed.

unset ZSH_DEBUG
# export ZSH_DEBUG=true

function find_yadr() {
  yadr=`fdfind -H .yadr $HOME | head | sed 's/\/\.yadr//'`
  export yadr
}
export yadr="/home/pmorgan/tools/dotfiles"

# autoload -U promptinit
# promptinit
# prompt adam1
# find_yadr

# Configuration
for config_file ($yadr/zsh/*.zsh) {
  if [[ -v ZSH_DEBUG ]]; then
      echo $config_file
  fi
  source $config_file
}

# Put secret configuration settings in ~/.secrets
if [[ -a ~/.secrets ]] then
  source ~/.secrets
fi

# added by pipx (https://github.com/pipxproject/pipx)
export EDITOR=vim

#eval $(op signin petermorgan)

#source /root/.config/broot/launcher/bash/br

#homebrew
export BREW_HOME="/home/linuxbrew/.linuxbrew/bin"
export PATH="$PATH:$BREW_HOME"

# starship
eval "$(starship init zsh)"

#zoxide
eval "$(zoxide init zsh)"

[ -f ~/.resh/shellrc ] && source ~/.resh/shellrc # this line was added by RESH (Rich Enchanced Shell History)

source /home/pmorgan/.local/share/phylum/zshrc

export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

#AWSume alias to source the AWSume script
alias awsume="source \$(pyenv which awsume)"

#Auto-Complete function for AWSume
_awsume() {
    local cur prev opts
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    opts=$(awsume-autocomplete)
    COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
    return 0
}
